import React from "react";
import { StyleProp, ViewStyle } from "react-native";
import {
  AlertCircle,
  AlertTriangle,
  Armchair,
  BarChart2,
  BarChart3,
  Box,
  Calendar,
  Camera,
  CameraOff,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Cloud,
  Database,
  Download,
  Upload,
  Edit2,
  ExternalLink,
  Eye,
  FileText,
  HardDrive,
  Inbox,
  IndianRupee,
  Info,
  Laptop,
  LayoutDashboard,
  Lock,
  LogOut,
  MapPin,
  Maximize2,
  Monitor,
  Package,
  Pencil,
  Plus,
  Printer,
  QrCode,
  RefreshCw,
  ScanLine,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldOff,
  Smartphone,
  Square,
  Tablet,
  Tag,
  Trash2,
  TrendingUp,
  Tv,
  User,
  UserCheck,
  Wrench,
  X,
  type LucideIcon as LucideIconType,
} from "lucide-react-native";

export {
  AlertCircle,
  AlertTriangle,
  Armchair,
  BarChart2,
  BarChart3,
  Box,
  Calendar,
  Camera,
  CameraOff,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Cloud,
  Database,
  Download,
  Upload,
  Edit2,
  ExternalLink,
  Eye,
  FileText,
  HardDrive,
  Inbox,
  IndianRupee,
  Info,
  Laptop,
  LayoutDashboard,
  Lock,
  LogOut,
  MapPin,
  Maximize2,
  Monitor,
  Package,
  Pencil,
  Plus,
  Printer,
  QrCode,
  RefreshCw,
  ScanLine,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldOff,
  Smartphone,
  Square,
  Tablet,
  Tag,
  Trash2,
  TrendingUp,
  Tv,
  User,
  UserCheck,
  Wrench,
  X,
};

const ICON_REGISTRY: Record<string, LucideIconType> = {
  // Common names & legacy Feather kebab-case mappings
  package: Package,
  box: Box,
  laptop: Laptop,
  desktop: HardDrive,
  "hard-drive": HardDrive,
  monitor: Monitor,
  tv: Tv,
  phone: Smartphone,
  smartphone: Smartphone,
  tablet: Tablet,
  furniture: Armchair,
  armchair: Armchair,
  square: Square,
  equipment: Wrench,
  tool: Wrench,
  wrench: Wrench,
  other: Package,

  // Navigation & Actions
  search: Search,
  x: X,
  plus: Plus,
  maximize: ScanLine,
  "scan-line": ScanLine,
  camera: Camera,
  "camera-off": CameraOff,
  settings: Settings,
  "bar-chart-2": BarChart3,
  "bar-chart": BarChart3,
  "layout-dashboard": LayoutDashboard,
  "trending-up": TrendingUp,

  // Admin & Status
  user: User,
  "user-check": UserCheck,
  "edit-2": Pencil,
  pencil: Pencil,
  "trash-2": Trash2,
  trash: Trash2,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-off": ShieldOff,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  check: Check,
  "check-circle": CheckCircle2,
  "check-circle-2": CheckCircle2,
  info: Info,

  // Chevrons
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,

  // UI Utilities
  eye: Eye,
  "map-pin": MapPin,
  "log-out": LogOut,
  cloud: Cloud,
  database: Database,
  inbox: Inbox,
  clock: Clock,
  calendar: Calendar,
  "refresh-cw": RefreshCw,
  download: Download,
  tag: Tag,
  "dollar-sign": IndianRupee,
  "indian-rupee": IndianRupee,
  "external-link": ExternalLink,
  printer: Printer,
  "share-2": Share2,
  lock: Lock,
  "file-text": FileText,
};

export interface LucideIconProps {
  name?: string | null;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: StyleProp<ViewStyle>;
}

export function LucideIcon({
  name,
  size = 20,
  color = "currentColor",
  strokeWidth = 2,
  style,
}: LucideIconProps) {
  if (!name) {
    return <Package size={size} color={color} strokeWidth={strokeWidth} style={style} />;
  }

  // Normalize name: lowercase and trim
  const normalized = name.trim().toLowerCase();
  const Component = ICON_REGISTRY[normalized] ?? Package;

  return <Component size={size} color={color} strokeWidth={strokeWidth} style={style} />;
}

export default LucideIcon;
